<?php
/**
 * ここにアプリ共通の定数を記述してください
 * 
 * @version   2015/02/19 -
 * @author    -
 * @since     2015/02/19
 * @copyright (C)2015 CROOZ All Rights Reserved
 */
define('APP_SYSTEM_TYPE', 'crooz');
define('APP_ROOT_PATH', '/');
define('ABSOLUTE_PATH', '/');
define('APP_SESSION_NAME', PATH_APP_TYPE);
define('APP_OFFICIAL_SITE',			false); //公式、非公式 [true|false]

/**
 * デフォルトのView返却形式
*/
define('APP_DEFAULT_VIEW_TYPE', VIEW_TYPE_HTML);